version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_example_project
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - example_project_data:/var/lib/mysql

volumes:
  example_project_data: